services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - 8080:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - ENV=dev
      - WEBUI_AUTH=False
      - ENABLE_OPENAI_API=False
      - ENABLE_OLLAMA_API=True
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    volumes:
      - ./open-webui:/Users/james/.ollama/models
    restart: unless-stopped
